### PR TITLE
Post Go-API import modifications

### PR DESCRIPTION
**Pull request by dentarg**
### WHY are these changes introduced?

https://github.com/cloudamqp/terraform-provider-cloudamqp/pull/282 imported https://github.com/84codes/go-api with history

https://github.com/cloudamqp/terraform-provider-cloudamqp/pull/273 makes some changes to the library code, the commits are cherry-picked from that branch

### WHAT is this pull request doing?

- Directly use go-api client library in the provider
- Remove the dependancy to separated go-api client library
- Clean up code and logging.
- More coherent code structure
  - Declare variable within var()
  - Make request
  - Switch statement to handle response

### HOW can this pull request be tested?

- [x] Test with Go-VCR test fixtures and subset of new tests

### CODE REVIEW

**Comment by dentarg** [comment]
Oh, the changes to `cloudamqp/` and `go.mod` and `go.sum` is missing. They're part of https://github.com/cloudamqp/terraform-provider-cloudamqp/commit/1727c2b4c6fd9afc56f697a8ea08440a1f0d7c80 that also imported `api/` files, so I never attempted to cherry-pick that.

**Comment by dentarg** [comment]
I extracted those changes by hand and added them here. CI is green 🥳 

Please test this as I haven't @tbroden84  :)

**Comment by tbroden84** [comment]
@dentarg GJ! Will do.

**Review by tbroden84 — APPROVED** [review]
Tried a subset of the tests with real requests together with some manual ones. Looking good to me.

List of the subset tests used.
TestAccAlarm_Basic
TestAccInstance_Basic
TestAccExtraDiskSize_AWS_Basic
TestAccIntegrationLog_Basic
TestAccRabbitMqConfiguration_Basic
TestAccFirewall_Basic
TestAccVpcConnect_AWS_Basic
TestAccVpcConnect_GCP_Basic
TestAccVpcConnect_Azure_Basic

**Pull request merged**
