### PR TITLE
Import Go-API client library with history

### PR DESCRIPTION
**Pull request by dentarg**
I used https://github.com/newren/git-filter-repo (I installed it from Homebrew; `brew install git-filter-repo`)

This was the steps I took:

```shell
mkdir repo-merge-terraform
cd repo-merge-terraform
gh repo clone cloudamqp/terraform-provider-cloudamqp
gh repo clone 84codes/go-api
cd go-api
git filter-repo --path api/
cd ../terraform-provider-cloudamqp
git remote add go-api ../go-api
git fetch go-api
git co -b go-api-branch go-api/main
git co main
git co -b import/go-api
git merge --allow-unrelated-histories -m "Import go-api repo" go-api-branch
git push -u
```

Full log at https://gist.github.com/dentarg/373595c415bf1a634b0f4bc6ea8f5cec

### CODE REVIEW

**Comment by dentarg** [comment]
I think you can do everything you did in https://github.com/cloudamqp/terraform-provider-cloudamqp/pull/273 @tbroden84  in this branch? Or perhaps as a pull request to this branch. Or just merge this one and make a new pull request with the changes needed to use the imported stuff.

**Comment by dentarg** [comment]
Oh I see. We only want the `api/` directory from https://github.com/84codes/go-api. That should also be doable.

**Comment by dentarg** [comment]
> Oh I see. We only want the `api/` directory from https://github.com/84codes/go-api. That should also be doable.

Done

**Comment by tbroden84** [comment]
@dentarg nice. Think it would be easier to move the changes from #273 into a new PR after this been merged.

**Comment by dentarg** [comment]
We can cherry-pick them, I did so and pushed this branch https://github.com/cloudamqp/terraform-provider-cloudamqp/compare/import-go-api-plus-modifications

It is probably nice to have them in its own PR thought, makes it more clear what we did after import.

**Comment by dentarg** [comment]
> We can cherry-pick them, I did so and pushed this branch https://github.com/cloudamqp/terraform-provider-cloudamqp/compare/import-go-api-plus-modifications

I removed this branch as we now have https://github.com/cloudamqp/terraform-provider-cloudamqp/pull/284

**Pull request merged**
