### PR TITLE
Add vpc_subnet and rmq_version parameters when creating instances

### PR DESCRIPTION
**Pull request by sheax0r**
This is a preliminary pull request. I have not yet tested this, because I don't have billing set up yet,  I can't create dedicated instances that allow `rmq_version` and `vpc_subnet` parameters.

I should be able to test it out early next week.

### CODE REVIEW

**Comment by jacobscunn07** [comment]
Were you able to test if this works @sheax0r ?

**Comment by sheax0r** [comment]
@jacobscunn07 unfortunately, the project I was working on when I wrote this has ended. I ultimately handled my need for rabbitmq servers manually, by just passing URLs for them as inputs to my terraform scripts.

My apologies for letting this one lapse. I'm not working on anything related to this now, and I doubt I'll be able to get back to this any time soon. I still think this is likely to "work", but testing is probably the biggest part of developing, and I haven't done that here.

**Comment by tbroden84** [comment]
Both parameters have been enabled during creation.

**Comment by kzap** [comment]
@tbroden84 do these parameters matter during updating, rmq_version doesn't seem to do anything to an instance when its modified

**Comment by tbroden84** [comment]
@kzap No, only during initial creation.

**Pull request closed without merging**
