### PR TITLE
fix various spelling issues

### PR DESCRIPTION
**Pull request by heydonovan**
takes care of this issue as well: https://github.com/cloudamqp/terraform-provider-cloudamqp/issues/101

### CODE REVIEW

**Comment by dentarg** [comment]
Thanks for the PR! Looks good, but can you update the commit to not change any file in `vendor/`? Those changes should be applied over at https://github.com/84codes/go-api 

(And then we can update the vendored stuff accordingly here (or we remove, see https://github.com/cloudamqp/terraform-provider-cloudamqp/issues/100))

**Comment by heydonovan** [comment]
You got it! I've reverted those changes. :v:

**Comment by heydonovan** [comment]
Opened up a PR within the go-api repo: https://github.com/84codes/go-api/pull/13

**Comment by dentarg** [comment]
Thanks!

**Pull request merged**
